example.organization.property: "I AM THE DEFAULT ORGANIZATION SERVICE"
example.property: "I AM IN THE DEFAULT"
#spring.jpa.database: "MYSQL"
#spring.datasource.platform:  "mysql"
spring.jpa.show-sql: "true"
spring.database.driverClassName: "com.mysql.cj.jdbc.Driver"
spring.datasource.url: "jdbc:mysql://127.0.0.1:3306/microservice_demo?useSSL=false"
spring.datasource.username: "root"
spring.datasource.password: "{cipher}36e03d81e8066a432c880ad3abdc74d52c7bbefbdc04283921ee8965afefad0e"
#spring.datasource.testWhileIdle: "true"
spring.datasource.type: "com.alibaba.druid.pool.DruidDataSource"
#spring.datasource.validationQuery: "SELECT 1"
#spring.jpa.properties.hibernate.dialect: "org.hibernate.dialect.MySQL5Dialect"
#redis.server: "redis"
#redis.port: "6379"
#signing.key: "345345fsdfsf5345"

#spring:
#  datasource:
#    password: 123456
#    username: root
#    url: jdbc:mysql://127.0.0.1:3306/microservice_demo?useSSL=false
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    type: com.alibaba.druid.pool.DruidDataSource